'''
Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million, find the sum of the
even-valued terms.
'''
# Simple fibonacci generator


def fibo_gen(maxi=4 * 10 ** 16):
    a, b = 0, 1
    while(a < maxi):
        yield a
        a, b = b, a + b
fib = [i for i in fibo_gen() if i % 2 == 0]

n = input()     # sum of how many numbers ?
t1 = filter(lambda x: x <= n, fib)
print(sum(t1))
